services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: steamdb
      POSTGRES_USER: steamuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - steamnet

  steam-api:
    image: ghcr.io/jensprog/steam-api:latest
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://steamuser:${POSTGRES_PASSWORD}@postgres/steamdb
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      CORS_ORIGINS: ${CORS_ORIGINS}
      STEAM_API_KEY: ${STEAM_API_KEY}
    depends_on:
      - postgres
    networks:
      steamnet:
        ipv4_address: 172.20.0.10

  steam-data:
    image: ghcr.io/jensprog/steam-data:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_API_BASE_URL: ${NUXT_PUBLIC_API_BASE_URL}
      NUXT_API_BASE_URL: ${NUXT_API_BASE_URL}
    ports:
      - "3000:3000"
    networks:
      - steamnet

networks:
  steamnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres_data:
